name: Node.js CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile
        context: .

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: malekazaouzi/nodejs-todo:latest

    - name: Deploy to production
      run: |
        # Script or command to deploy your Dockerized application
        docker-compose up -d
